compatibility_date = "2022-12-05"
main = "src/index.ts"
type = "webpack"
workers_dev = true
node_compat = true 

[build]
command = "yarn"
[build.upload]
format = "service-worker"


name = "giveaways-dev"
node_compat = true
[vars]
TWITER_API_KEY="JUy0DpggZ8FUsFA7nZfoXnLJy"
TWITER_API_SECRET="pML9OL7GlJvAjvqvlVhe8oJbrele7ptU1K2cTGj3kXDy9h3Df5"
TWITTER_BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAANtckAEAAAAAAv6njkro3%2Bd%2BNyqbJp%2FXOVqgZfY%3DW1AjriFqkvRIFre8RzMbzIZC4QDEVSiPqFjUz8DKeMxW9irdoY"
TWITTER_APP_ID=26238171
TWITTER_BASE_URL="https://api.twitter.com/2/tweets/"
WORKER_BASE_URL="https://giveaway.lfgames.workers.dev/"

[env.staging]
name = "giveaways-staging"
[env.staging.vars]

[env.production]
name = "giveaways"
node_compat = true
[env.production.vars]

