/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v1 from "./v1";
export type { v1 };
export type { GameFactoryV2 } from "./GameFactoryV2";
export type { GameV2 } from "./GameV2";
