/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abstracts from "./abstracts";
export type { abstracts };
import type * as games from "./games";
export type { games };
import type * as giveways from "./giveways";
export type { giveways };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as keepers from "./keepers";
export type { keepers };
import type * as libraries from "./libraries";
export type { libraries };
import type * as multicall from "./multicall";
export type { multicall };
